[package]
name = "slide-puzzle-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
pathfinding = "4.9.1"
enigo = "0.2.0"
terminal-menu = "3.0.0"
crossterm = "0.25.0"
livesplit-hotkey = "0.7.0"